In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving data.csv to data.csv

In [ ]:
df = pd.read_csv("data.csv", encoding="ISO-8859-1")

In [ ]:
df.head(5)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [ ]:
df.columns=df.columns.str.strip()
print(df.columns)

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

**DATA CLEANING AND MANIPULATION**

In [ ]:
print(df.isnull().values.any())

True

In [ ]:
df["Description"] = df["Description"].fillna("Unknown") #replace missing decription with Unknown

In [ ]:
df['CustomerID']=df['CustomerID'].fillna(-1)

In [ ]:
df[df.isnull().any(axis=1)] # to know which rows have missing values

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

In [ ]:
df['InvoiceDate']=pd.to_datetime(df['InvoiceDate'])

In [ ]:
df.head(3)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom

In [ ]:
print(df.dtypes)

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
dtype: object

In [ ]:
df["Quantity"] = pd.to_numeric(df["Quantity"])
df["UnitPrice"] = pd.to_numeric(df["UnitPrice"])

In [ ]:
print(df[["Quantity", "UnitPrice"]].isnull().sum())

Quantity     0
UnitPrice    0
dtype: int64

In [ ]:
df["TotalSales"]= (df['Quantity']* df["UnitPrice"]).round(2)

In [ ]:
df.head(3)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalSales
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00

In [ ]:
df.duplicated().sum() #identify any duplicate rows

np.int64(5268)

In [ ]:
df = df.drop_duplicates() #drop duplicates

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 536641 entries, 0 to 541908
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    536641 non-null  object
 1   StockCode    536641 non-null  object
 2   Description  536641 non-null  object
 3   Quantity     536641 non-null  int64
 4   InvoiceDate  536641 non-null  datetime64[ns]
 5   UnitPrice    536641 non-null  float64
 6   CustomerID   536641 non-null  float64
 7   Country      536641 non-null  object
 8   TotalSales   536641 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(4)
memory usage: 40.9+ MB

In [ ]:
df["IsCancelled"] = df["InvoiceNo"].astype(str).str.startswith("C")
print(df["IsCancelled"].value_counts())

IsCancelled
False    527390
True       9251
Name: count, dtype: int64

In [ ]:
df["IsValidSale"] = (
    (df["Quantity"] > 0) &
    (df["UnitPrice"] > 0) &
    (df["TotalSales"] > 0) &
    (df["IsCancelled"] == False)
)

In [ ]:
print(df["IsValidSale"].value_counts())

IsValidSale
True     524874
False     11767
Name: count, dtype: int64

In [ ]:
df["CustomerID"] = df["CustomerID"].fillna(-1).astype(int)

In [ ]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalSales,IsCancelled,IsValidSale
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,False,True
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,False,True
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00,False,True
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,False,True
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,False,True
...,...,...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680,France,10.20,False,True
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France,12.60,False,True
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France,16.60,False,True
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France,16.60,False,True
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France,14.85,False,True

In [ ]:
df.to_csv("cleaned_dataset.csv",index=False)

In [ ]:
from google.colab import files

files.download("cleaned_dataset.csv")

**RFM DATASET**

In [ ]:
rfm_dataset = df[
    (df["CustomerID"] != -1) &
    (df["IsValidSale"] == True)
].copy()

In [ ]:
print("Cleaned transactions:", df.shape)
print("RFM transactions:", rfm_dataset.shape)

Cleaned transactions: (536641, 11)
RFM transactions: (392688, 11)

In [ ]:
rfm_dataset.to_csv("rfm_dataset.csv", index=False)

In [ ]:
from google.colab import files

files.download("rfm_dataset.csv")

In [ ]:
valid_sales_df = df[df["IsValidSale"] == True].copy()
valid_sales_df.to_csv("valid_sales_dataset.csv", index=False)

In [ ]:
valid_sales_df.to_csv("valid_sales_dataset.csv",index=False)

In [ ]:
from google.colab import files

files.download("valid_sales_dataset.csv")

In [ ]:
print("Cleaned dataset:", df.shape)
print("Valid sales dataset:", valid_sales_df.shape)
print("RFM dataset:", rfm_dataset.shape)

Cleaned dataset: (536641, 11)
Valid sales dataset: (524874, 11)
RFM dataset: (392688, 11)